# Generated by Django 5.2.14 on 2026-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_is_verified_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified_owner',
            field=models.BooleanField(default=True),
        ),
    ]
